name: Pruebas De Rendimiento con JMeter

on:
    push:
        branches: [main]

jobs:
    performance-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del Código
              uses: actions/checkout@v4

            - name: Configurar JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Descargar y Configurar JMeter
              id: jmeter-setup
              run: |
                JMETER_VERSION="5.6.3"
                JMETER_TGZ="apache-jmeter-${JMETER_VERSION}.tgz"
                JMETER_DIR="apache-jmeter-${JMETER_VERSION}"
                JMETER_INSTALL_PATH="${{ runner.temp }}/${JMETER_DIR}"

                echo "Descargando JMeter"
                wget "https://dlcdn.apache.org//jmeter/binaries/${JMETER_TGZ}"

                echo "Descomprimir JMeter"
                tar -xzf ${JMETER_TGZ} -C ${{ runner.temp }}

                echo "${JMETER_INSTALL_PATH}/bin" >> $GITHUB_PATH
            
            - name: Verificando instalación de JMeter
              run: |
                jmeter --version
                echo "JMeter verificado correctamente"
            
            - name: Configurar Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.8'

            - name: Instalar Dependencias Python
              run: pip install
              working-directory: ./

            - name: Levantar la Aplicación Web
              run: |
                cd app/
                setsid python server.py > ../server_app.log 2>&1 &
                echo "Servidor web iniciado."
                sleep 5
                echo "Chequeo de Logs"
                cat ../server_app.log || echo "server_app.log no existe."
              working-directory: ./

            - name: Esperar a que la Aplicación esté lista
              run: |
                sleep 5
                curl --retry 12 --retry-delay 5 --fail http://localhost:5000/ || \
                { echo "La aplicación web no respondió."; \
                  cat server_app.log; \
                  exit 1; }
                echo "La aplicación web está lista." 

            - name: Ejecutar Pruebas de JMeter
              run: |
                rm -rf jmeter-reports
                mkdir jmeter-reports

                jmeter -n -t tests/rendimiento-test.jmx -l jmeter-reports/results.jtl -e -o jmeter-reports/html-report

            - name: Subir Reporte HTML
              uses: actions/upload-artifact@v4
              if: always()
              with: 
                name: jmeter-performance-report
                path: jmeter-reports/html-report

            - name: Finalizar Job
              if: always()
              run: |
                if ${{ job.status == 'success'}}; then
                    echo "Las pruebas de rendimiento se completaron sin problemas."
                else
                    echo "Las pruebas fallaron rotundamente."
                fi
            